name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: linux
    steps:
     - name: print Greetings
       run: echo "Hello World"
     - name: GoodBye 
       run: echo "GoodBye"
